version: '2'
services:
  web:
    image: kabueye/gatsby-starter-standard-blog:production
    build:
      context: ./
      dockerfile: Dockerfile.production
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "80:80"